{
  "os": "linux",
  "dist": "trusty",
  "group": "stable",
  "script": ["yarn test"],
  "node_js": "node",
  "language": "node_js",
  "after_success": ["yarn coveralls", "npm pack"],
  "before_script": ["yarn", "yarn build"],
}
